//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightCommander.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FlightCommander.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Connect 的本地化字符串。
        /// </summary>
        public static string btnConnect {
            get {
                return ResourceManager.GetString("btnConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disconnect 的本地化字符串。
        /// </summary>
        public static string btnDisconnect {
            get {
                return ResourceManager.GetString("btnDisconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load from file... 的本地化字符串。
        /// </summary>
        public static string btnLoad {
            get {
                return ResourceManager.GetString("btnLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Quit 的本地化字符串。
        /// </summary>
        public static string btnQuit {
            get {
                return ResourceManager.GetString("btnQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Read PID 的本地化字符串。
        /// </summary>
        public static string btnRead {
            get {
                return ResourceManager.GetString("btnRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Record 的本地化字符串。
        /// </summary>
        public static string btnRecord {
            get {
                return ResourceManager.GetString("btnRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save to file... 的本地化字符串。
        /// </summary>
        public static string btnSave {
            get {
                return ResourceManager.GetString("btnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scan 的本地化字符串。
        /// </summary>
        public static string btnScan {
            get {
                return ResourceManager.GetString("btnScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop 的本地化字符串。
        /// </summary>
        public static string btnStop {
            get {
                return ResourceManager.GetString("btnStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Write PID 的本地化字符串。
        /// </summary>
        public static string btnWrite {
            get {
                return ResourceManager.GetString("btnWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Port 的本地化字符串。
        /// </summary>
        public static string lblComPort {
            get {
                return ResourceManager.GetString("lblComPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Connection status:  的本地化字符串。
        /// </summary>
        public static string lblConnectionStatus {
            get {
                return ResourceManager.GetString("lblConnectionStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error rate:  的本地化字符串。
        /// </summary>
        public static string lblErrorRate {
            get {
                return ResourceManager.GetString("lblErrorRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FrameCount:  的本地化字符串。
        /// </summary>
        public static string lblFrameCount {
            get {
                return ResourceManager.GetString("lblFrameCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Debug 的本地化字符串。
        /// </summary>
        public static string tabDebug {
            get {
                return ResourceManager.GetString("tabDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Deck 的本地化字符串。
        /// </summary>
        public static string tabDeck {
            get {
                return ResourceManager.GetString("tabDeck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Map 的本地化字符串。
        /// </summary>
        public static string tabMap {
            get {
                return ResourceManager.GetString("tabMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PID Tuning 的本地化字符串。
        /// </summary>
        public static string tabParams {
            get {
                return ResourceManager.GetString("tabParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        public static string tabSettings {
            get {
                return ResourceManager.GetString("tabSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Toggles 的本地化字符串。
        /// </summary>
        public static string tabToggles {
            get {
                return ResourceManager.GetString("tabToggles", resourceCulture);
            }
        }
    }
}
